"""
AgentScope (Alibaba DAMO Academy) - Distributed Multi-Agent Ops Pipeline
Demonstrates: Pipeline-based multi-agent coordination, structured messaging,
distributed agent execution, and pipeline DAG for ops workflows.

AgentScope uses: Agents communicate via Msg objects through a pipeline,
supporting parallel execution, distributed deployment, and rich model configs.
"""

import os
from datetime import datetime
from typing import Optional

import agentscope
from agentscope.agents import DialogAgent, UserAgent
from agentscope.pipelines import (
    SequentialPipeline,
    WhileLoopPipeline,
    IfElsePipeline,
    ForLoopPipeline,
)
from agentscope.message import Msg
from agentscope.service import (
    ServiceToolkit,
    execute_shell_command,
    get_current_directory,
    list_directory_content,
)

# ─────────────────────────────────────────────
# AgentScope Initialization
# ─────────────────────────────────────────────
MODEL_CONFIGS = [
    {
        "config_name": "ollama_llama3",
        "model_type": "ollama_chat",
        "model_name": os.getenv("OLLAMA_MODEL", "llama3"),
        "options": {"temperature": 0.1, "num_predict": 4096},
        "host": "http://ollama:11434",
        "keep_alive": "5m",
    },
    {
        "config_name": "openai_gpt4o",
        "model_type": "openai_chat",
        "model_name": "gpt-4o",
        "api_key": os.getenv("OPENAI_API_KEY", ""),
        "temperature": 0.1,
    },
]

ACTIVE_MODEL = "ollama_llama3" if os.getenv("USE_LOCAL_LLM", "true").lower() == "true" else "openai_gpt4o"

agentscope.init(model_configs=MODEL_CONFIGS)

# ─────────────────────────────────────────────
# Service Toolkit (safe ops tools)
# ─────────────────────────────────────────────
def check_docker_status(service_name: str) -> str:
    """Check if a Docker container is running and healthy."""
    import subprocess
    result = subprocess.run(
        ["docker", "inspect", "--format",
         "{{.State.Status}} | Health: {{.State.Health.Status}}", service_name],
        capture_output=True, text=True, timeout=10
    )
    return result.stdout.strip() or f"Service {service_name} not found"


def get_system_metrics() -> dict:
    """Get current system CPU, memory, and disk metrics."""
    import psutil
    return {
        "cpu_percent": psutil.cpu_percent(interval=1),
        "memory_percent": psutil.virtual_memory().percent,
        "disk_percent": psutil.disk_usage('/').percent,
        "timestamp": datetime.utcnow().isoformat(),
    }


def generate_ops_report(findings: str, recommendations: str) -> str:
    """Generate a formatted ops report."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    return f"""
# Ops Report — {timestamp}

## Findings
{findings}

## Recommendations
{recommendations}

---
*Generated by AgentScope Ops Pipeline*
"""


service_toolkit = ServiceToolkit()
service_toolkit.add(check_docker_status)
service_toolkit.add(get_system_metrics)
service_toolkit.add(generate_ops_report)

# ─────────────────────────────────────────────
# Agent Definitions
# ─────────────────────────────────────────────
monitor_agent = DialogAgent(
    name="MonitorAgent",
    model_config_name=ACTIVE_MODEL,
    sys_prompt=(
        "You are a systems monitoring agent. Your job is to collect and analyze "
        "system health metrics. Use the available tools to check service status "
        "and system metrics. Report your findings in a structured format: "
        "STATUS (healthy/degraded/critical), METRICS (key values), ALERTS (if any)."
    ),
    use_memory=True,
)

analyst_agent = DialogAgent(
    name="AnalystAgent",
    model_config_name=ACTIVE_MODEL,
    sys_prompt=(
        "You are a root cause analysis agent. Given monitoring data, you identify "
        "the root cause of issues using the '5 Whys' methodology. "
        "Output format: ROOT_CAUSE, EVIDENCE, CONFIDENCE (high/medium/low)."
    ),
    use_memory=True,
)

remediation_agent = DialogAgent(
    name="RemediationAgent",
    model_config_name=ACTIVE_MODEL,
    sys_prompt=(
        "You are a remediation agent. Given a root cause analysis, you propose "
        "and execute safe remediation steps. Always list steps in order of "
        "IMPACT (low→high). Mark any step needing human approval with [HUMAN_APPROVAL_REQUIRED]."
    ),
    use_memory=True,
)

report_agent = DialogAgent(
    name="ReportAgent",
    model_config_name=ACTIVE_MODEL,
    sys_prompt=(
        "You are a reporting agent. Synthesize all findings, analysis, and actions "
        "into a clear, executive-friendly ops report. Include: Summary, Root Cause, "
        "Actions Taken, Recommendations, and Next Steps."
    ),
    use_memory=True,
)

# ─────────────────────────────────────────────
# Pipeline: Sequential Ops Workflow
# ─────────────────────────────────────────────
def build_ops_pipeline():
    """Build a sequential ops pipeline: Monitor → Analyse → Remediate → Report."""
    
    pipeline = SequentialPipeline(
        agents=[monitor_agent, analyst_agent, remediation_agent, report_agent]
    )
    return pipeline


# ─────────────────────────────────────────────
# Pipeline: Conditional Escalation
# ─────────────────────────────────────────────
def build_escalation_pipeline():
    """Build an if-else pipeline that escalates critical issues."""
    
    def is_critical(msg: Msg) -> bool:
        content = str(msg.content).lower()
        return "critical" in content or "p0" in content or "down" in content

    escalation_agent = DialogAgent(
        name="EscalationAgent",
        model_config_name=ACTIVE_MODEL,
        sys_prompt=(
            "You handle critical escalations. Notify the on-call engineer "
            "and generate an immediate incident ticket. Draft the PagerDuty alert message."
        ),
        use_memory=False,
    )

    pipeline = IfElsePipeline(
        condition_func=is_critical,
        if_body_agent=escalation_agent,
        else_body_agent=report_agent,
    )
    return pipeline


# ─────────────────────────────────────────────
# Pipeline: Retry Loop
# ─────────────────────────────────────────────
def build_retry_pipeline(max_retries: int = 3):
    """Build a while-loop pipeline that retries health checks until stable."""
    
    retry_count = {"n": 0}

    def should_retry(msg: Msg) -> bool:
        retry_count["n"] += 1
        content = str(msg.content).lower()
        return "degraded" in content and retry_count["n"] < max_retries

    pipeline = WhileLoopPipeline(
        loop_body_agent=monitor_agent,
        condition_func=should_retry,
    )
    return pipeline


# ─────────────────────────────────────────────
# Distributed Agent Mode (AgentScope RPC)
# ─────────────────────────────────────────────
def create_distributed_agents():
    """
    Create agents in distributed (RPC) mode for production deployment.
    Each agent runs as a separate process/container.
    """
    # In production: use agentscope.server and launch_server_from_config
    # monitor_agent_dist = monitor_agent.to_dist(
    #     host="monitor-agent-service",
    #     port=12001,
    #     lazy_launch=False,
    # )
    # analyst_agent_dist = analyst_agent.to_dist(
    #     host="analyst-agent-service",
    #     port=12002,
    # )
    # Requires: docker-compose services for each agent
    print("Distributed mode: requires AgentScope RPC server setup")
    print("See: https://agentscope.io/en/tutorial/rpc.html")


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────
if __name__ == "__main__":
    print("AgentScope Ops Pipeline\n" + "="*40)

    # Build and run the sequential pipeline
    pipeline = build_ops_pipeline()

    # Kick off with an ops investigation task
    initial_msg = Msg(
        name="Operator",
        content=(
            "Investigate the current health of the AgentOps stack. "
            "Check all services, identify any issues, and provide "
            "remediation recommendations."
        ),
        role="user",
    )

    print(f"\nStarting pipeline with task: {initial_msg.content}\n")
    
    # Run through the pipeline
    current_msg = initial_msg
    for agent in [monitor_agent, analyst_agent, remediation_agent, report_agent]:
        print(f"\n--- {agent.name} ---")
        current_msg = agent(current_msg)
        print(f"Output: {str(current_msg.content)[:300]}...")

    print("\n" + "="*40)
    print("Pipeline complete.")
    print("\nFinal Report:")
    print(current_msg.content)
